VARS = dict()
VARS["FA_USE_INI"] = "Should use the .ini file"
VARS["FA_INI_FILE_PATH"] = "Path to the .ini file"
VARS["FA_SERVER"] = "Front Arena server"
VARS["FA_PORT"] = "Front Arena port"
VARS["FA_USERNAME"] = "Front Arena User Password, required if single-sign-on is off"
VARS["FA_SSO"] = "Is single-sign-on on for the user"
VARS["FA_PASSWORD"] = "Front Arena Password"
VARS["FA_AEL_PYTHON_PATH"] = "Path to Front Arena ael_python.exe"
